dsite_name: Catherine Slaughter
remote_theme: catieslaughts/minimal
title: Catherine Slaughter, M.Sc.
description: She/Her <br> Astrophysicist | Scicomm Enthusiast <br> Imagine Others Complexly
logo: images_pdfs/photos/badlands_cropped.jpg
