site_name: Catherine Slaughter
remote_theme: catieslaughts/minimal
title: Catherine Slaughter
description: She/Her <br> Proto-Astrophysicist | Scicomm Enthusiast <br><a href="mailto:catherine.m.slaughter@gmail.com"> <i class="fas fa-envelope"></i> Catherine.M.Slaughter@gmail.com</a> <br><a href="https://orcid.org/0000-0002-5752-3780" target="_blank"> <i class="fab fa-orcid"></i>ORCiD</a> <br><a href="https://github.com/CatieSlaughts" target="_blank"> <i class="fab fa-github" ></i>Github</a>
logo: images_pdfs/IMG_0386.png
